// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Date': string;
  'DateContainer': string;
  'Date__date': string;
  'Date__label': string;
  'Field': string;
  'Field__name': string;
  'Field__value': string;
  'OrderedCallItem': string;
  'OrderedCallItem__bottom': string;
  'OrderedCallItem__container': string;
  'OrderedCallItem__deleteBtn': string;
}
declare var cssExports: CssExports;
export = cssExports;
