// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'GroupOrderedCalls': string;
  'GroupOrderedCalls__content': string;
  'GroupOrderedCalls__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
