// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Navbar': string;
  'Navbar__icon': string;
  'Navbar__item': string;
  'Navbar__link': string;
  'UserView': string;
  'UserView__chevron': string;
  'UserView__description': string;
  'UserView__greeting': string;
  'UserView__header': string;
  'UserView__img': string;
  'UserView__name': string;
  'UserView__navbar': string;
  'UserView__navbar_open': string;
}
declare var cssExports: CssExports;
export = cssExports;
