// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AdminLayout': string;
  'AdminLayout__content': string;
  'AdminLayout__footer': string;
  'AdminLayout__header': string;
  'AdminLayout__page': string;
  'AdminLayout__sidebar': string;
  'AdminLayout__wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
