// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Advantage': string;
  'Advantage__description': string;
  'Advantage__img': string;
  'Advantage__label': string;
  'Advantage__title': string;
  'Advantages': string;
  'Advantages__itemContainer': string;
}
declare var cssExports: CssExports;
export = cssExports;
