// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'MainView': string;
  'MainView__action': string;
  'MainView__bg': string;
  'MainView__btn': string;
  'MainView__container': string;
  'MainView__description': string;
  'MainView__imgBg': string;
  'MainView__slogan': string;
  'MainView__title': string;
  'Modal': string;
  'Modal__closeBtn': string;
  'Modal__content': string;
  'Modal__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
