// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'LocaleTabsRenderer': string;
  'Nav': string;
  'Nav__item': string;
  'Nav__link': string;
  'Nav__link_active': string;
  'Tabs': string;
  'Tabs__tab': string;
  'Tabs__tab_active': string;
}
declare var cssExports: CssExports;
export = cssExports;
