// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'LocaleTabsRenderer__TabTitle': string;
}
declare var cssExports: CssExports;
export = cssExports;
