// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Group': string;
  'Group__content': string;
  'Group__title': string;
  'Properties': string;
  'Properties__toolbar': string;
  'Property': string;
  'Property__content': string;
  'Property__title': string;
  'Property_asGroup': string;
}
declare var cssExports: CssExports;
export = cssExports;
