// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Form': string;
  'Form__btn': string;
  'Form__control': string;
  'Form__error': string;
  'Form__form': string;
  'Form__group': string;
  'Form__label': string;
  'Signin': string;
  'Signin__container': string;
  'Signin__form': string;
  'Signin__logo': string;
}
declare var cssExports: CssExports;
export = cssExports;
