// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Portfolio': string;
  'PortfolioGroup': string;
  'PortfolioGroup__content': string;
  'PortfolioGroup__title': string;
  'Portfolio__date': string;
  'Portfolio__description': string;
  'Portfolio__imageContainer': string;
  'Portfolio__mainImage': string;
  'Portfolio__mockupImage': string;
  'Portfolio__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
