// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'News': string;
  'News__text': string;
  'News__title': string;
  'Title': string;
  'Title__date': string;
  'Title__text': string;
}
declare var cssExports: CssExports;
export = cssExports;
