// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Date': string;
  'Date__day': string;
  'Date__month': string;
  'Date__monthYearContainer': string;
  'Date__year': string;
  'News': string;
  'NewsItem': string;
  'NewsItem__content': string;
  'NewsItem__date': string;
  'NewsItem__img': string;
  'NewsItem__link': string;
  'News__recentNews': string;
  'RecentNews': string;
  'RecentNewsContainer': string;
  'RecentNews__date': string;
  'RecentNews__img': string;
  'RecentNews__title': string;
  'RestNews__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
