// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Cell': string;
  'Cell__title': string;
  'Cell__value': string;
  'Row': string;
  'Row__backBtn': string;
  'Row__container': string;
  'Row__toolbar': string;
}
declare var cssExports: CssExports;
export = cssExports;
