// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Node': string;
  'Node__content': string;
  'Node__icon': string;
  'Node__toolbar': string;
  'Node__toolbarBtn': string;
}
declare var cssExports: CssExports;
export = cssExports;
