// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Spinner': string;
  'Spinner__spinner': string;
  'spinner-border': string;
}
declare var cssExports: CssExports;
export = cssExports;
