// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Form': string;
  'FormBtn': string;
  'FormControl': string;
  'FormErrorMessage': string;
  'FormGroup': string;
  'FormGroup_error': string;
}
declare var cssExports: CssExports;
export = cssExports;
