export var GET_TABLE_ACTION = 'GET_TABLE_ACTION';
export var GET_TABLE_HEADERS_ACTION = 'GET_TABLE_HEADERS_ACTION';
export var GET_TABLE_ROWS_ACTION = 'GET_TABLE_ROWS_ACTION';
export var GET_TABLE_ROW_ACTION = 'GET_TABLE_ROW_ACTION';
//# sourceMappingURL=types.js.map