export const GET_TABLE_ACTION = 'GET_TABLE_ACTION';
export const GET_TABLE_HEADERS_ACTION = 'GET_TABLE_HEADERS_ACTION';
export const GET_TABLE_ROWS_ACTION = 'GET_TABLE_ROWS_ACTION';

export const GET_TABLE_ROW_ACTION = 'GET_TABLE_ROW_ACTION';

export const UPDATE_TABLE_ROW_ACTION = 'UPDATE_TABLE_ROW_ACTION';
export const SAVE_TABLE_ROW_ACTIONS = 'SAVE_TABLE_ROW_ACTIONS';
