// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Equipment': string;
  'Equipment__descriptionContainer': string;
  'Equipment__image': string;
  'Equipment__title': string;
  'Gallery': string;
  'GalleryWrapper': string;
  'Gallery__imgContainer': string;
  'Gallery__zoomBtn': string;
  'Wrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
