// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Equipments': string;
  'Equipments__nav': string;
  'Navigation': string;
  'Navigation__item': string;
  'Navigation__link': string;
  'Navigation__link_active': string;
}
declare var cssExports: CssExports;
export = cssExports;
