// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Navbar': string;
  'Navbar__content': string;
  'Navbar__navbar': string;
  'Navbar__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
