// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'NavbarItem': string;
  'NavbarItem__chevron': string;
  'NavbarItem__chevron_open': string;
  'NavbarItem__icon': string;
  'NavbarItem__link': string;
}
declare var cssExports: CssExports;
export = cssExports;
