// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Address': string;
  'AddressContainer': string;
  'Address__companyName': string;
  'Address__item': string;
  'Address__title': string;
  'AskQuestion': string;
  'AskQuestion__form': string;
  'AskQuestion__title': string;
  'Contact': string;
  'ContactItems': string;
  'ContactItems__content': string;
  'ContactItems__item': string;
  'ContactItems__title': string;
  'Contact__content': string;
  'Contact__description': string;
  'Contact__title': string;
  'Map': string;
  'Map__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
