// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Modal': string;
  'Modal__closeBtn': string;
}
declare var cssExports: CssExports;
export = cssExports;
