// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Table': string;
  'TableManager': string;
  'TableManager__table': string;
  'TableManager__toolbar': string;
}
declare var cssExports: CssExports;
export = cssExports;
