// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'TableManager': string;
  'TableManager__table': string;
  'TableManager__toolbar': string;
  'button': string;
  'buttonGroup': string;
  'button_active': string;
}
declare var cssExports: CssExports;
export = cssExports;
