// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Item': string;
  'Item__cellName': string;
  'Item__cellValue': string;
  'Item__row': string;
  'Item__toolbar': string;
  'List': string;
}
declare var cssExports: CssExports;
export = cssExports;
