// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SingleImage': string;
  'SingleImage__toolbar': string;
}
declare var cssExports: CssExports;
export = cssExports;
