// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ImageModal': string;
  'ImageModal__buttons': string;
  'ImageModal__content': string;
  'ImageModal__dropArea': string;
  'ImageModal__dropAreaWrapper': string;
  'ImageModal__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
