// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ImageGallery': string;
  'Item': string;
  'Item__btn': string;
  'Item__image': string;
  'Item__toolbar': string;
  'SingleImage__uploadBtn': string;
  'SingleImage__uploadBtn_section': string;
}
declare var cssExports: CssExports;
export = cssExports;
